version: '3.8'

services:
  postgresql19_za_alpha:
    container_name: postgresql19_za_alpha
    image: warkanum/postgresql19_za_alpha
    build:
      context: .
      dockerfile: Dockerfile
    user: "${DOCKER_UID}:${DOCKER_GID}"
    ports:
      - "5403:5435"
    volumes:
      - /tmp/postgresql19_za_alpha_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    shm_size: 8g
    deploy:
      resources:
        limits:
          memory: 10G
          cpus: '4'
