---
postgresql_build_packages:
  Debian:
    - build-essential
    - autoconf
    - automake
    - bison
    - flex
    - libreadline-dev
    - zlib1g-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libicu-dev
    - liblz4-dev
    - libzstd-dev
    - libcurl4-openssl-dev
    - libperl-dev
    - python3-dev
    - libkrb5-dev
    - libgeos-dev
    - libproj-dev
    - libgdal-dev
    - libjson-c-dev
    - libprotobuf-c-dev
    - libboost-all-dev
    - cargo
    - rustc
    - clang
    - libclang-dev
    - cmake
    - libtool
    - gettext
    - pkg-config
    - git
    - curl
    - ca-certificates
  RedHat:
    - gcc
    - gcc-c++
    - make
    - autoconf
    - automake
    - bison
    - flex
    - readline-devel
    - zlib-devel
    - openssl-devel
    - libxml2-devel
    - libxslt-devel
    - libicu-devel
    - lz4-devel
    - libzstd-devel
    - libcurl-devel
    - perl-devel
    - python3-devel
    - krb5-devel
    - geos-devel
    - proj-devel
    - gdal-devel
    - json-c-devel
    - protobuf-c-devel
    - boost-devel
    - cargo
    - rust
    - clang
    - llvm-devel
    - cmake
    - libtool
    - gettext
    - pkgconf-pkg-config
    - git
    - curl
    - ca-certificates
  Archlinux:
    - base-devel
    - autoconf
    - automake
    - bison
    - flex
    - readline
    - zlib
    - openssl
    - libxml2
    - libxslt
    - icu
    - lz4
    - zstd
    - curl
    - perl
    - python
    - krb5
    - geos
    - proj
    - gdal
    - json-c
    - protobuf-c
    - boost
    - rust
    - clang
    - cmake
    - libtool
    - gettext
    - pkgconf
    - git
  Gentoo:
    - sys-devel/gcc
    - sys-devel/make
    - sys-devel/autoconf
    - sys-devel/automake
    - sys-devel/bison
    - sys-devel/flex
    - dev-libs/openssl
    - dev-libs/libxml2
    - dev-libs/libxslt
    - dev-libs/icu
    - dev-libs/lz4
    - app-arch/zstd
    - net-misc/curl
    - dev-lang/perl
    - dev-lang/python
    - sys-libs/readline
    - sys-libs/zlib
    - dev-db/postgis
    - dev-cpp/boost
    - dev-lang/rust
    - sys-devel/clang
    - dev-util/cmake
    - sys-devel/libtool
    - sys-devel/gettext
    - dev-vcs/git
  Void:
    - base-devel
    - bison
    - flex
    - readline-devel
    - zlib-devel
    - openssl-devel
    - libxml2-devel
    - libxslt-devel
    - icu-devel
    - lz4-devel
    - libzstd-devel
    - curl-devel
    - perl
    - python3-devel
    - krb5-devel
    - geos-devel
    - proj-devel
    - gdal-devel
    - json-c-devel
    - protobuf-c-devel
    - boost-devel
    - autoconf
    - automake
    - cmake
    - libtool
    - gettext-devel
    - pkg-config
    - git
    - cargo
    - rust
    - clang
    - llvm-devel
