version: '3.8'

services:
  postgresql18_za:
    container_name: postgresql18_za
    image: warkanum/postgresql18_za
    build:
      context: .
      dockerfile: Dockerfile
    user: "${DOCKER_UID}:${DOCKER_GID}"
    ports:
      - "5403:5435"
    volumes:
      - /tmp/postgresql18_za_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    shm_size: 8g
    deploy:
      resources:
        limits:
          memory: 10G
          cpus: '4'
